language: groovy

jdk:
  - openjdk7
  - oraclejdk8

script:
  - ./gradlew clean build check uploadArchives -s
  - cd samples/jacoco-multi; ./gradlew clean check -s; cd ..

after_success:
  - ./gradlew cobertura coveralls -s
